### PR TITLE
Use field default value when loading configs from file

### PR DESCRIPTION
**Pull request by azazel75**
Hello Stephen, 

I found what seems a bug to me, but smells like intentional. I've added a test too, please take a look

What do you think?

cheers
Alberto

P.S. Your guidelines file doesn't follow your guidelines :-D

### CODE REVIEW

**Comment by stephen-bunn** [comment]
Out of curiosity what are things are conflicting in the `CONTRIBUTING.rst`? It's been a while since I've updated it.

**Comment by azazel75** [comment]
The length of the lines, it's way beyond 88 chars

**Comment by stephen-bunn** [comment]
Yeah that's what I thought. I meant for that to apply to Python source only. I'll update the language to that separately.

**Comment by azazel75** [comment]
Thanks Stephen, do you plan to do a release? I would be glad to have a released package to install.

BTW, Reading long lines in text file is as awkward as in program source files, why keep than so long? ;-)

**Comment by stephen-bunn** [comment]
I'll do a patch release tonight.

I stopped enforcing line length for rst since so much of it is auto generated from various tools. Too bad something like https://github.com/ambv/black doesn't exist for everything.

**Pull request merged**
